on:
  push:
    branches:
      - main
  schedule:
    - cron: "00 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Publish AUR
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.1
        with:
          pkgname: moonbit-bin
          pkgbuild: ./PKGBUILD
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ github.repository_owner }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_keyscan_types: rsa,ecdsa,ed25519
          commit_message: update
          force_push: "true"
          allow_empty_commits: false
