on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "00 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Update PKGBUILD
        run: |
          chmod +x generate_PKGBUILD.sh || true
          ./generate_PKGBUILD.sh

      - name: Publish AUR
        uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
        with:
          pkgname: moonbit-bin
          pkgbuild: ./PKGBUILD
          assets: moon.sh
          updpkgsums: true
          post_process: |
            rm -rf *.tar.gz
          commit_username: ${{ github.repository_owner }}
          commit_email: ${{ github.repository_owner }}@users.noreply.github.com
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_keyscan_types: rsa,ecdsa,ed25519
          commit_message: update
          force_push: "true"
          allow_empty_commits: false
